//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleInsurance_Employee.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Claim
    {
        [Display(Name = "Claim Number")]
        public int ClaimNumber { get; set; }

        [Display(Name = "Policy Number")]
        public int PolicyNumber { get; set; }

        [Display(Name = "Place Of Accident")]
        public string PlaceOfAccident { get; set; }

        [Display(Name = "Date Of Accident")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime DateOfAccident { get; set; }

        [Display(Name = "Insured Amount")]
        public Nullable<decimal> InsuredAmount { get; set; }

        [Display(Name = "Claimable Amount")]
        public decimal ClaimableAmount { get; set; }

        [Display(Name = "Status")]
        public string Status { get; set; }

        public virtual OrderPolicy OrderPolicy { get; set; }
    }
}
