//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleInsurance_Employee.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CompanyExpense
    {
        [Display(Name = "Company Expense ID")]
        public int CompanyExpenseID { get; set; }

        [Display(Name = "Date Of Expense")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime DateOfExpense { get; set; }

        [Display(Name = "Type Of Expense")]
        public string TypeOfExpense { get; set; }

        [Display(Name = "Amount Of Expense")]
        public decimal AmountOfExpense { get; set; }
    }
}
